In [1]:
import numpy as np
import sys
from itertools import combinations

In [3]:
momentum_grid = [[px, py, pz] for pz in range(-5, 6) for py in range(-5, 6) for px in range(-5, 6) if (pz==0) and (px>0) and ((np.sqrt(px**2+py**2+pz**2)<=5))]
momentum_grid = np.array(momentum_grid)
kinetic_energy_grid = np.array([np.sqrt((item**2).sum()) for item in momentum_grid])

In [7]:
(momentum_grid[0]**2).sum()**0.5

np.float64(4.123105625617661)

In [4]:
kinetic_energy_grid

array([4.12310563, 4.47213595, 5.        , 3.16227766, 3.60555128,
       4.24264069, 5.        , 2.23606798, 2.82842712, 3.60555128,
       4.47213595, 1.41421356, 2.23606798, 3.16227766, 4.12310563,
       1.        , 2.        , 3.        , 4.        , 5.        ,
       1.41421356, 2.23606798, 3.16227766, 4.12310563, 2.23606798,
       2.82842712, 3.60555128, 4.47213595, 3.16227766, 3.60555128,
       4.24264069, 5.        , 4.12310563, 4.47213595, 5.        ])

In [8]:
momentum_grid

array([[ 1, -4,  0],
       [ 2, -4,  0],
       [ 3, -4,  0],
       [ 1, -3,  0],
       [ 2, -3,  0],
       [ 3, -3,  0],
       [ 4, -3,  0],
       [ 1, -2,  0],
       [ 2, -2,  0],
       [ 3, -2,  0],
       [ 4, -2,  0],
       [ 1, -1,  0],
       [ 2, -1,  0],
       [ 3, -1,  0],
       [ 4, -1,  0],
       [ 1,  0,  0],
       [ 2,  0,  0],
       [ 3,  0,  0],
       [ 4,  0,  0],
       [ 5,  0,  0],
       [ 1,  1,  0],
       [ 2,  1,  0],
       [ 3,  1,  0],
       [ 4,  1,  0],
       [ 1,  2,  0],
       [ 2,  2,  0],
       [ 3,  2,  0],
       [ 4,  2,  0],
       [ 1,  3,  0],
       [ 2,  3,  0],
       [ 3,  3,  0],
       [ 4,  3,  0],
       [ 1,  4,  0],
       [ 2,  4,  0],
       [ 3,  4,  0]])

In [48]:
def cartesian_to_spherical(cart_vec):
    x, y, z = cart_vec
    rad = np.sqrt((cart_vec**2).sum())
    theta = np.arctan2(np.sqrt(x**2+y**2), z)
    phi = np.arctan2(y, x)
    return rad, theta, phi

# g factor for H_vv
def g_factor(p1, p2, q1, q2):
    absp1, tp1, pp1 = cartesian_to_spherical(p1)
    absp2, tp2, pp2 = cartesian_to_spherical(p2)
    absq1, tq1, pq1 = cartesian_to_spherical(q1)
    absq2, tq2, pq2 = cartesian_to_spherical(q2)
    fac1 = np.exp(-1j*pq1)*np.sin(tq1/2.)*np.cos(tq2/2.) - np.exp(-1j*pq2)*np.cos(tq1/2.)*np.sin(tq2/2.)
    fac2 = np.exp(1j*pp1)*np.sin(tp1/2.)*np.cos(tp2/2.) - np.exp(1j*pp2)*np.cos(tp1/2.)*np.sin(tp2/2.)
    return 2 * fac1 * fac2

In [49]:
kec_nt = []

for i1 in range(np2):
    p1 = ps[i1,:]
    for i2 in range(i1,np2):
        p2 = ps[i2,:]
        for i3 in range(np2):
            p3 = ps[i3,:]
            for i4 in range(i3,np2):
                p4 = ps[i4,:]
                pdiff = p1+p2-p3-p4
                if np.sum(np.abs(pdiff)) < 1e-7:
                    k1 = np.sqrt(np.dot(p1,p1))
                    k2 = np.sqrt(np.dot(p2,p2))
                    k3 = np.sqrt(np.dot(p3,p3))
                    k4 = np.sqrt(np.dot(p4,p4))
                    gf = g_factor(p1,p2,p3,p4)
                    if np.abs(k1+k2-k3-k4) < 1e-7 and np.abs(gf) > 1e-7:
                        if i1!=i3:
                            #print(i1, i2, i3, i4, p1, p2, p3, p4, p1+p2-p3-p4, np.abs(pdiff))
                            kec_nt.append([i1,i2,i3,i4])

In [50]:
kec_nt

[[0, 33, 1, 32],
 [0, 34, 2, 32],
 [1, 13, 3, 10],
 [1, 32, 0, 33],
 [1, 34, 2, 33],
 [2, 9, 4, 6],
 [2, 12, 6, 7],
 [2, 22, 3, 19],
 [2, 32, 0, 34],
 [2, 33, 1, 34],
 [3, 10, 1, 13],
 [3, 19, 2, 22],
 [3, 29, 4, 28],
 [3, 30, 5, 28],
 [3, 31, 6, 28],
 [4, 6, 2, 9],
 [4, 12, 7, 9],
 [4, 28, 3, 29],
 [4, 30, 5, 29],
 [4, 31, 6, 29],
 [5, 28, 3, 30],
 [5, 29, 4, 30],
 [5, 31, 6, 30],
 [6, 7, 2, 12],
 [6, 21, 7, 19],
 [6, 28, 3, 31],
 [6, 29, 4, 31],
 [6, 30, 5, 31],
 [7, 9, 4, 12],
 [7, 19, 6, 21],
 [7, 25, 8, 24],
 [7, 26, 9, 24],
 [7, 27, 10, 24],
 [8, 24, 7, 25],
 [8, 26, 9, 25],
 [8, 27, 10, 25],
 [9, 24, 7, 26],
 [9, 25, 8, 26],
 [9, 27, 10, 26],
 [10, 24, 7, 27],
 [10, 25, 8, 27],
 [10, 26, 9, 27],
 [11, 21, 12, 20],
 [11, 22, 13, 20],
 [11, 23, 14, 20],
 [12, 20, 11, 21],
 [12, 22, 13, 21],
 [12, 23, 14, 21],
 [12, 31, 19, 24],
 [13, 20, 11, 22],
 [13, 21, 12, 22],
 [13, 23, 14, 22],
 [13, 34, 19, 28],
 [14, 20, 11, 23],
 [14, 21, 12, 23],
 [14, 22, 13, 23],
 [19, 24, 12, 31],
 [1

In [28]:
kec_nt = np.array(kec_nt)
Nkec = len(kec_nt)

#ninit = np.sort(np.array([0,5,10,25,28,33])) # N=6
ninit = np.sort(np.array([0,5,10,12,20,25,28,33])) # N=8
#ninit = np.sort(np.array([0,5,8,10,12,20,25,26,28,33])) # N=10

Nn = len(ninit)

pinit = np.sum(ps[ninit], axis=0)
keinit = np.sum(kes[ninit])

In [29]:
print(f'Reference state is {ninit}')
print(f'Reference state total momentum: {pinit}')
print(f'Reference state kinetic energy: {keinit}')

Reference state is [ 0  5 10 12 20 25 28 33]
Reference state total momentum: [16.  0.  0.]
Reference state kinetic energy: 26.95100454752356


In [30]:
binom = np.array(list(combinations([i for i in range(Nn)],2)))
Nbinom = len(binom)

In [31]:
def check(state):
    ans = True
    for i in range(len(state)-2):
        if np.var(state[i:i+3]) < 1e-7:
            ans = False
    return ans

In [32]:
def apply(state):
    newstate = []
    for i in range(Nbinom):
        k = np.array([state[binom[i,0]], state[binom[i,1]]])
        for j in range(Nkec):
            if np.sum(np.abs(k-kec_nt[j,:2]))==0:
                state_i = state.copy()
                state_i[binom[i,0]] = kec_nt[j,2]
                state_i[binom[i,1]] = kec_nt[j,3]
                state_i = np.sort(state_i)
                if check(state_i):
                    newstate.append(state_i)
    return np.array(newstate)

In [33]:
nnewstate = 10  # > 1 to enter the while loop
p_states = np.array([ninit])
newstate1 = np.array([np.zeros(Nn), ninit])
trial = 0

while nnewstate > 1:
    print(f'---------------- H^{trial+1} ----------------')
    newstate2 = np.zeros((1,Nn))
    #newstate3 = np.zeros((1,Nn))
    for i in range(1,len(newstate1)):
        newi = apply(newstate1[i])
        if len(newi) > 0:
            newstate2 = np.append(newstate2, newi, axis=0)
       
    newstate1 = np.array([np.zeros(Nn)])
    for j in range(1,len(newstate2)):
        dist = np.sum(np.abs(p_states - newstate2[j]), axis=1)
        if np.min(dist) > 1e-7:
            p_states = np.append(p_states, [newstate2[j].astype(int)], axis=0)
            newstate1 = np.append(newstate1, [newstate2[j]], axis=0)
    nnewstate = len(newstate1)
    print(f'Number of new states(mod flavor choice) at this round: {nnewstate-1}')
    print(f'Number of states(mod flavor choice) visited so far: {len(p_states)}')
        
    trial += 1

---------------- H^1 ----------------
Number of new states(mod flavor choice) at this round: 4
Number of states(mod flavor choice) visited so far: 5
---------------- H^2 ----------------
Number of new states(mod flavor choice) at this round: 8
Number of states(mod flavor choice) visited so far: 13
---------------- H^3 ----------------
Number of new states(mod flavor choice) at this round: 10
Number of states(mod flavor choice) visited so far: 23
---------------- H^4 ----------------
Number of new states(mod flavor choice) at this round: 6
Number of states(mod flavor choice) visited so far: 29
---------------- H^5 ----------------
Number of new states(mod flavor choice) at this round: 1
Number of states(mod flavor choice) visited so far: 30
---------------- H^6 ----------------
Number of new states(mod flavor choice) at this round: 0
Number of states(mod flavor choice) visited so far: 30


In [34]:
n_states = 0

for i in range(len(p_states)):
    totp = np.sum(ps[p_states[i]], axis=0)
    totke = np.sum(kes[p_states[i]])
    nstate = 2**Nn/4**(Nn-len(set(p_states[i])))
    strs = ' '.join([str(x) for x in p_states[i]]) + '\n'
    n_states += nstate
    if np.sum(np.abs(totp-pinit)) > 1e-7 or np.abs(totke-keinit) > 1e-7:
        print('Total momentum or kinetic energy is not conserved!')

In [35]:
print(f'Number of momentum modes pair with conserved P and E is {len(p_states)}')
print(f'Number of states with conserved P,E, and arbitrary flavor contents is {n_states:.0f}')
bins_visited = np.sort(np.array(list(set(p_states.flatten()))))
print(f'Activated momentum modes:')
print(bins_visited)

Number of momentum modes pair with conserved P and E is 30
Number of states with conserved P,E, and arbitrary flavor contents is 6528
Activated momentum modes:
[ 0  1  3  5  8 10 11 12 13 20 21 22 25 27 28 30 32 33]
